//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AccountingDocumentPrint
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<long> Debtor { get; set; }
        public Nullable<long> Creditor { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<int> TemporaryDocumentNumber { get; set; }
        public Nullable<int> PermanantDocumentNumber { get; set; }
        public Nullable<bool> IsPermenant { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> AccountingDocumentId { get; set; }
        public string DetailedAccount { get; set; }
        public string CertainAccount { get; set; }
        public string TotalAccount { get; set; }
        public string DocumentType { get; set; }
    }
}
